name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
    - name: Create SHA Container Tag
      id: sha_tag
      run: |
        tag=$(cut -c 1-7 <<< $GITHUB_SHA)
        echo "::set-output name=tag::$tag"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./tinyy_backend
        push: true
        tags: |
          ghcr.io/den4200/tinyy_backend:latest
          ghcr.io/den4200/tinyy_backend:${{ steps.sha_tag.outputs.tag }}

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./tinyy_frontend
        push: true
        tags: |
          ghcr.io/den4200/tinyy_frontend:latest
          ghcr.io/den4200/tinyy_frontend:${{ steps.sha_tag.outputs.tag }}
